[project]
name = "hass-auto-backup"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "homeassistant>=2024.11.2",
]

[dependency-groups]
docs = [
    "mkdocs-material>=9.5.44",
]
